"""empty message

Revision ID: 24f15d64d7db
Revises: 7cdef6b8dac3
Create Date: 2019-09-21 16:17:38.316476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f15d64d7db'
down_revision = '7cdef6b8dac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('director', sa.String(length=32), nullable=True),
    sa.Column('starring', sa.String(length=128), nullable=True),
    sa.Column('showtime', sa.String(length=128), nullable=True),
    sa.Column('brief', sa.String(length=256), nullable=True),
    sa.Column('duration', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie1')
    # ### end Alembic commands ###
