"""创建Student

Revision ID: 658c00e5a850
Revises: 1a90cf358a68
Create Date: 2019-09-20 16:04:39.095345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658c00e5a850'
down_revision = '1a90cf358a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
